---
# the reasoning for using 127.0.1.1 and not ansible_default_ipv4.address is, that if a host is
# changing between lan/wifi or has a dynamic ip, hardcoding the ip would be bad!
- name: Ensure correct but unaesthetic /etc/hosts entry (point hostname to 127.0.0.1)
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^127.0.1.1"
    line: "127.0.1.1	{{ ansible_hostname }}.{{ basic.local_domain }} {{ ansible_hostname }}" # noqa no-tabs

- name: Ensure correct but unaesthetic /etc/hosts entry (point hostname to ::1)
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^::1		{{ ansible_hostname }}"
    line: "::1		{{ ansible_hostname }}.{{ basic.local_domain }} {{ ansible_hostname }}" # noqa no-tabs

- name: Remove raspberrypi entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "raspberrypi"
    line: ""

- name: Fix FQDN hostname
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hosts_file_ip_address }}"
    line: "{{ hosts_file_ip_address }}	{{ hosts_file_fqdn }} {{ hostname }}"
    state: present
  when: ip_address is defined
